import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const S = process.env.HOME + '/.claude/skills/figma-auto-html-merge/scripts';
const { chromium } = createRequire(S + '/x.js')('playwright-core');
const { launchOptions } = await import(pathToFileURL(S + '/browser.mjs').href);
const browser = await chromium.launch({ ...launchOptions(), args: [ '--disable-gpu' ] });
const page = await browser.newPage({ viewport: { width: Number(process.argv[3]), height: 900 } });
await page.goto(process.argv[2], { waitUntil: 'load' });
const out = await page.evaluate((sel) => [...document.querySelectorAll(sel)].map(el => { const r = el.getBoundingClientRect(); return [Math.round(r.top + scrollY), Math.round(r.height), el.textContent.trim().slice(0, 24)]; }), process.argv[4]);
console.log(JSON.stringify(out));
await browser.close();
